{{- if .Values.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-operations-web
  labels:
    app: ph-ee-operations-web
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ph-ee-operations-web
  template:
    metadata:
      labels:
        app: ph-ee-operations-web
      annotations:
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-operations-web
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "{{ .Values.limits.memory }}"
              cpu: "{{ .Values.limits.cpu }}"
            requests:
              memory: "{{ .Values.requests.memory }}"
              cpu: "{{ .Values.requests.cpu }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 4200
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 4200
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: "PH_OPS_BACKEND_SERVER_URL"
              value: "{{ .Values.backend.PH_OPS_BACKEND_SERVER_URL }}"
            - name: "PH_VOU_BACKEND_SERVER_URL"
              value: "{{ .Values.backend.PH_VOU_BACKEND_SERVER_URL }}"
            - name: "PH_ACT_BACKEND_SERVER_URL"
              value: "{{ .Values.backend.PH_ACT_BACKEND_SERVER_URL }}"
            - name: "PH_PLATFORM_TENANT_ID"
              value: "{{ .Values.backend.PH_PLATFORM_TENANT_ID }}"
            - name: "PH_PLATFORM_TENANT_IDS"
              value: "{{ .Values.backend.PH_PLATFORM_TENANT_IDS }}"
            - name: "PH_REGISTERING_INSTITUTION_ID"
              value: "{{ .Values.backend.PH_REGISTERING_INSTITUTION_ID }}"
            - name: "PH_AUTH_ENABLED"
              value: "{{ .Values.auth.PH_AUTH_ENABLED }}"
            - name: "PH_OAUTH_ENABLED"
              value: "{{ .Values.auth.PH_OAUTH_ENABLED }}"
            - name: "PH_OAUTH_TYPE"
              value: "{{ .Values.auth.PH_OAUTH_TYPE }}"
            - name: "PH_OAUTH_SERVER_URL"
              value: "{{ .Values.auth.PH_OAUTH_SERVER_URL }}"
            - name: "PH_OAUTH_REALM"
              value: "{{ .Values.auth.PH_OAUTH_REALM }}"
            - name: "PH_OAUTH_CLIENT_ID"
              value: "{{ .Values.auth.PH_OAUTH_CLIENT_ID }}"
            - name: "PH_OAUTH_CLIENT_SECRET"
              value: "{{ .Values.auth.PH_OAUTH_CLIENT_SECRET }}"
            - name: "PH_OAUTH_BASIC_AUTH"
              value: "{{ .Values.auth.PH_OAUTH_BASIC_AUTH }}"
            - name: "PH_OAUTH_BASIC_AUTH_TOKEN"
              value: "{{ .Values.auth.PH_OAUTH_BASIC_AUTH_TOKEN }}"
            - name: "PH_DEFAULT_LANGUAGE"
              value: "{{ .Values.PH_DEFAULT_LANGUAGE }}"
            - name: "PH_SUPPORTED_LANGUAGES"
              value: "{{ .Values.PH_SUPPORTED_LANGUAGES }}"
{{- if .Values.extraEnvs | default .Values.deployment.extraEnvs }}
{{ toYaml ( .Values.extraEnvs | default .Values.deployment.extraEnvs ) | indent 12 }}
{{- end }}
          volumeMounts:
{{- if .Values.deployment.config }}
{{ toYaml .Values.deployment.config | indent 12 }}
{{- end }}
      volumes:
        - name: ph-ee-operations-web-config
          configMap:
            name: ph-ee-operations-web-config
{{- end }}