{{- if .Values.operations_web.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-operations-web
  annotations:
{{- if .Values.operations_web.ingress.annotations }}
{{ toYaml .Values.operations_web.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.operations_web.hostname }}"
      http:
        paths:
          - path: "{{ .Values.operations_web.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.operations_web.ingress.backend }}
{{ toYaml .Values.operations_web.ingress.backend | indent 14 }}
{{- end }}

  tls:
  - hosts:
    - "{{ .Values.operations_web.wildcardhostname }}"
    secretName: "{{ .Values.operations_web.tls }}"
{{- end }}