apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: bulk-closedloop-secret
type: Opaque
data:
  aws-access-key: {{ .Values.aws.access_key | b64enc }}
  aws-secret-key: {{ .Values.aws.secret_key | b64enc }}