{{ if and (.Files.Glob "setup-files/kong-keycloak-realm.json") (.Values.keycloak.enabled) }}

apiVersion: v1
kind: Secret
metadata:
  name: realm-secret
# labels:
#  app: keycloak
type: Opaque 
data: 
{{ (.Files.Glob "setup-files/kong-keycloak-realm.json").AsSecrets | indent 2 }}

{{ end }} 
