{{- if .Values.ph_ee_connector_ams_mifos.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-connector-ams-mifos
  annotations:
{{- if .Values.ph_ee_connector_ams_mifos.ingress.annotations }}
{{ toYaml .Values.ph_ee_connector_ams_mifos.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.ph_ee_connector_ams_mifos.hostname }}"
      http:
        paths:
          - path: "{{ .Values.ph_ee_connector_ams_mifos.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.ph_ee_connector_ams_mifos.ingress.backend }}
{{ toYaml .Values.ph_ee_connector_ams_mifos.ingress.backend | indent 14 }}
{{- end }} 

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}