{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-operations-web"
  labels:
    app: ph-ee-operations-web
spec:
  replicas: {{ .Values.operations_web.replicas }}
  selector:
    matchLabels:
      app: ph-ee-operations-web
  template:
    metadata:
      labels:
        app: ph-ee-operations-web
      annotations:
{{- if .Values.operations_web.deployment.annotations }}
{{ toYaml .Values.operations_web.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-operations-web
          image: "{{ .Values.operations_web.image }}:{{ .Values.operations_web.imageTag }}"
          imagePullPolicy: "{{ .Values.operations_web.imagePullPolicy }}"
          ports:
            - containerPort: 4200
          resources:
            limits:
              memory: "{{ .Values.operations_web.limits.memory }}"
              cpu: "{{ .Values.operations_web.limits.cpu }}"
            requests:
              memory: "{{ .Values.operations_web.requests.memory }}"
              cpu: "{{ .Values.operations_web.requests.cpu }}"
          volumeMounts:
{{- if .Values.operations_web.deployment.config }}
{{ toYaml .Values.operations_web.deployment.config | indent 12 }}
{{- end }}
      volumes:
        - name: ph-ee-operations-web-config
          configMap:
            name: ph-ee-operations-web-config
{{- end }}            
