apiVersion: v2
description: PaymentHub EE Barebone Edition
type: application
name: ph-ee-g2psandbox
version: 1.5.1
appVersion: 1.5.1

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine-1.13.1-SNAPSHOT
  version: 1.13.1-SNAPSHOT

- name: account_mapper
  version: 1.0.0
  repository: "file://../identity-account-mapper/account-mapper"
