# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.roster_connector.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: {{ template " ph-ee-connector-ams-roster.fullname" . }}
  labels:
    app: {{ template " ph-ee-connector-ams-roster.fullname" . }}
spec:
  replicas: {{ .Values.roster_connector.replicas }}
  selector:
    matchLabels:
      app: {{ template " ph-ee-connector-ams-roster.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template " ph-ee-connector-ams-roster.fullname" . }}
      annotations:
{{- if .Values.roster_connector.deployment.annotations }}
{{ toYaml .Values.roster_connector.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      affinity: {{ toYaml .Values.roster_connector.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.roster_connector.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.roster_connector.tolerations | default .Values.roster_connector.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.roster_connector.priorityClassName }}
      priorityClassName: {{ .Values.roster_connector.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template " ph-ee-connector-ams-roster.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.roster_connector.terminationGracePeriod }}
      containers:
        - name: ph-ee-connector-ams-roster
          image: "{{ .Values.roster_connector.image }}:{{ .Values.roster_connector.imageTag }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: "{{ .Values.roster_connector.imagePullPolicy }}"
          resources: {{ toYaml ( .Values.messagegateway.resources | default .Values.messagegateway.deployment.resources ) | nindent 10 }}
      {{- if .Values.messagegateway.imagePullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.messagegateway.imagePullSecrets | indent 8 }}
        {{- end }}
          livenessProbe:
{{ toYaml .Values.messagegateway.livenessProbe | indent 10 }}
          readinessProbe:
{{ toYaml .Values.messagegateway.readinessProbe | indent 10 }}

          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.roster_connector.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"
            - name: "AMS_LOCAL_ENABLED"
              value: "{{ .Values.roster_connector.ams.local.enabled }}"
            - name: "PESACORE_AUTH-HEADER"
              valueFrom:
                secretKeyRef:
                  name: "roster-secret"
                  key: "auth-token"
            - name: "PESACORE_BASE-URL"
              value: "{{ .Values.roster_connector.pesacore.base_url }}"
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.roster_connector.LOGGING_LEVEL_ROOT }}"
{{- if .Values.roster_connector.extraEnvs | default .Values.roster_connector.deployment.extraEnvs }}
{{ toYaml ( .Values.roster_connector.extraEnvs | default .Values.roster_connector.deployment.extraEnvs ) | indent 8 }}
{{- end }}
          envFrom: {{ toYaml ( .Values.roster_connector.envFrom | default .Values.roster_connector.deployment.envFrom ) | nindent 10 }}
          securityContext: {{ toYaml ( .Values.roster_connector.podSecurityContext | default .Values.roster_connector.deployment.securityContext ) | nindent 10 }}

          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
{{- if .Values.roster_connector.deployment.config }}
{{ toYaml .Values.roster_connector.deployment.config | indent 12 }}
{{- end }}            
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
            - -timeout=120s
            - -wait
            - tcp://{{ .Values.operations_app.datasource.host }}:3306
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
    {{ tpl .Values.extraInitContainers . | indent 6 }}
          {{- else }}
    {{ toYaml .Values.extraInitContainers | indent 6 }}
          {{- end }}
          {{- end }}          
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
     {{- if .Values.roster_connector.extraVolumeMounts | default .Values.roster_connector.deployment.extraVolumeMounts }}
  {{ toYaml ( .Values.roster_connector.extraVolumeMounts | default .Values.roster_connector.deployment.extraVolumeMounts ) | indent 8 }}
          {{- end }}
        {{- if .Values.roster_connector.extraContainers }}
  {{ tpl .Values.roster_connector.extraContainers . | indent 6 }}
        {{- end }}              
{{- end }}              
