{{- if .Values.managedServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template " ph-ee-connector-mpesa.serviceAccount" . }}
  annotations:
    {{- with .Values.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ template " ph-ee-connector-mpesa.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
{{- end -}}