version: 2.1
description: "Check for docker image availability wrt jira story and do helm upgrade"
orbs:
  helm: circleci/helm@2.0.1
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
commands:
  docker-image-availability-check-and-upgrade:
    parameters:
      namespace:
        default: ""
        description: |
          The kubernetes namespace that should be used.
        type: string
      release-name:
        default: ""
        description: |
          Specify a name for the release.
        type: string
      cluster-name:
        default: "sit"
        type: string
      aws-region:
        default: "${REGION}"
        type: string
      service-file-path:
        default: https://raw.githubusercontent.com/openMF/ph-ee-env-labs/master/.circleci/services.txt
        type: string
      chart-base-url:
        default: https://fynarfin.io/images
        type: string
      chart-name:
        default: ph-ee-g2psandbox-fynarfin
        type: string
      chart-version:
        default: 0.2.0
        type: string

    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: <<parameters.cluster-name>>
          aws-region: <<parameters.aws-region>>
      - helm/install-helm-client:
          version: "v3.8.2"
      - run:
          name: fetch docker images and helm upgrade
          environment:
            ORB_CHART_BASE_URL: << parameters.chart-base-url >>
            ORB_CHART_NAME: << parameters.chart-name >>
            ORB_CHART_VERSION: << parameters.chart-version >>
            ORB_PARAM_NAMESPACE: << parameters.namespace >>
            ORB_PARAM_RELEASE_NAME: << parameters.release-name >>
            JIRA_STORY: ''
            JIRA_STORY_DIR: ''
            VALUES_TO_OVERRIDE: ''
            SERVICE_FILE_PATH: << parameters.service-file-path>>
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then
              
              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
              
              
              function get_services_from_file() {
                file=$1
                while IFS= read -r line || [ -n "$line" ]; do
                  echo "Processing line: $line"
                  generate_values_to_override $line
                done < "$file"
              }
            
              function generate_values_to_override() {
                PREFIX="docker.io/"
                if check_for_image_tag ${2#"$PREFIX"} ${JIRA_STORY}; then
                    echo "$1=$2:$JIRA_STORY"
                    VALUES_TO_OVERRIDE+=$(echo "$1=$2:$JIRA_STORY"),
                else
                    VALUES_TO_OVERRIDE+=$(echo "$1=$2:latest"),
                fi
              }
              function check_for_image_tag(){
                echo "checking for service with image tag $1 $2"
                curl --silent -f --head -lL https://hub.docker.com/v2/repositories/$1/tags/$2/ > /dev/null
              }
              
              echo $SERVICE_FILE_PATH
              wget $SERVICE_FILE_PATH
              filename=$(basename "$SERVICE_FILE_PATH")
              get_services_from_file $filename
            fi 
              
            if [ -n "${VALUES_TO_OVERRIDE}" ]; then
                VALUES_TO_OVERRIDE=$(echo --set ${VALUES_TO_OVERRIDE::-1})
                echo "VALUES_TO_OVERRIDE: $VALUES_TO_OVERRIDE"
            fi

            if [ -n "${ORB_PARAM_NAMESPACE}" ]; then
                ORB_PARAM_NAMESPACE=$(echo --namespace ${ORB_PARAM_NAMESPACE})
            fi
            if [ -n "${JIRA_STORY}" ]; then
              JIRA_STORY=-$(echo $JIRA_STORY)
            fi
            
            # Generating the chart url for deployment
            # chart: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin/ph-ee-g2psandbox-fynarfin-0.2.0.tgz"
            
            ORB_PARAM_CHART=$(echo "$ORB_CHART_BASE_URL$JIRA_STORY_DIR/$ORB_CHART_NAME$JIRA_STORY/$ORB_CHART_NAME-$ORB_CHART_VERSION$JIRA_STORY.tgz")
            
            # add-repo: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin"
            
            ORB_PARAM_REPO=$(echo "$ORB_CHART_BASE_URL$JIRA_STORY_DIR/$ORB_CHART_NAME$JIRA_STORY")
            echo helm repo add "${ORB_PARAM_RELEASE_NAME}" "${ORB_PARAM_REPO}"
            helm repo add "${ORB_PARAM_RELEASE_NAME}" "${ORB_PARAM_REPO}"

            helm repo update
            echo "helm upgrade --install ${VALUES_TO_OVERRIDE} ${ORB_PARAM_RELEASE_NAME} ${ORB_PARAM_CHART} ${ORB_PARAM_NAMESPACE}"
            helm upgrade --install ${VALUES_TO_OVERRIDE} ${ORB_PARAM_RELEASE_NAME} ${ORB_PARAM_CHART} ${ORB_PARAM_NAMESPACE}

jobs:
  docker-image-availability-check-and-upgrade:
    docker:
      - image: cimg/openjdk:17.0.0
    parameters:
      namespace:
        type: string
        default: ""
      release-name:
        default: ""
        type: string
      cluster-name:
        default: "sit"
        type: string
      aws-region:
        default: "$REGION"
        type: string
      service-file-path:
        default: https://raw.githubusercontent.com/openMF/ph-ee-env-labs/master/.circleci/services.txt
        type: string
      chart-base-url:
        default: https://fynarfin.io/images/
        type: string
      chart-name:
        default: ph-ee-g2psandbox-fynarfin
        type: string
      chart-version:
        default: 0.2.0
        type: string

    steps:
      - docker-image-availability-check-and-upgrade:
          namespace: <<parameters.namespace>>
          release-name: <<parameters.release-name>>
          cluster-name: <<parameters.cluster-name>>
          aws-region: <<parameters.aws-region>>
          chart-base-url: https://fynarfin.io/images/
          chart-name: ph-ee-g2psandbox-fynarfin
          chart-version: 0.2.0

