apiVersion: v1
appVersion: "operations-app: v1.0.0; gsma: v1.0.0; notifications: v1.0.0; paygops: v1.0.0; roster: v10.0.0; mpesa: v1.0.0; operations-web: v1.0.0; mojaloop: v1.0.0; slcb: v1.0.0; importer-es: v1.0.0; message-gateway: v1.0.0; ams-mifos: v1.0.0; bulk: v1.0.0; channel: v1.0.0; rdbms: v1.0.0; zeebe-ops: v1.0.0;"
description: PaymentHub EE Engine
name: ph-ee-engine
version: 0.0.1-SNAPSHOT
