apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-creator-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: paymenthub
roleRef:
  kind: ClusterRole
  name: job-creator-role
  apiGroup: rbac.authorization.k8s.io
rules:
- apiGroups: [""]
  resources: ["clusterroles"]
  verbs: ["get", "list", "create", "delete", "update"]