{{- if .Values.post-installation-job.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-creator-role
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
{{- end }}