apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-mpesa"
  labels:
    app: ph-ee-connector-mpesa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-mpesa
  template:
    metadata:
      labels:
        app: ph-ee-connector-mpesa
      annotations:
        deployTime: "{{ .Values.deployTime }}"
    spec:
      containers:
        - name: ph-ee-connector-mpesa
          image: "{{ .Values.mpesa.image }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /actuator/health/liveness
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 30
            readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 30
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.mpesa.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"
            - name: "MPESA_LOCAL_HOST"
              value: "https://mpesa.ibank.financial"
          resources:
            limits:
              memory: "400M"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ph-ee-connector-mpesa
  name: ph-ee-connector-mpesa
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-mpesa
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ph-ee-connector-mpesa
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "{{ .Values.mpesa.hostname }}"
      http:
        paths:
          - backend:
              serviceName: ph-ee-connector-mpesa
              servicePort: 80
