{{- if .Values.operations.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-operations-web
  labels:
    app: ph-ee-operations-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-operations-web
  template:
    metadata:
      labels:
        app: ph-ee-operations-web
    spec:
      containers:
        - name: ph-ee-operations-web
          image: "{{ .Values.operations_web.image }}"
          resources:
            limits:
              memory: "1536M"
          ports:
            - containerPort: 4200
          volumeMounts:
            - name: ph-ee-operations-web-config
              mountPath: "/app/src/assets/configuration.properties"
              subPath: "configuration.properties"
      volumes:
        - name: ph-ee-operations-web-config
          configMap:
            name: ph-ee-operations-web-config

---
apiVersion: v1
data:
  configuration.properties: |
    oauth.enabled true
    oauth.basicAuth true
    oauth.basicAuthToken Y2xpZW50Og==
    oauth.serverUrl http://{{ .Values.identity.hostname }}
    serverUrl http://{{ .Values.operations_app.hostname }}
kind: ConfigMap
metadata:
  name: ph-ee-operations-web-config

---
kind: Service
apiVersion: v1
metadata:
  name: ph-ee-operations-web
spec:
  selector:
    app: ph-ee-operations-web
  ports:
    - protocol: TCP
      port: 4200

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ph-ee-operations-web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "{{ .Values.operations_web.webhost }}"
      http:
        paths:
          - backend:
              serviceName: ph-ee-operations-web
              servicePort: 4200
{{- end }}
