{{- if .Values.operations.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-importer-rdbms
  labels:
    app: ph-ee-importer-rdbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-importer-rdbms
  template:
    metadata:
      labels:
        app: ph-ee-importer-rdbms
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: ph-ee-importer-rdbms
          image: us.icr.io/phee-ns/importer-rdbms
          ports:
            - containerPort: 8000
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_operations.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

{{- end }}
