# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.ph_ee_connector_mojaloop.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: {{ template " ph-ee-connector-mojaloop-java.fullname" . }}
  labels:
    app: {{ template " ph-ee-connector-mojaloop-java.fullname" . }}
spec:
  replicas: {{ .Values.ph_ee_connector_mojaloop.replicas }}
  selector:
    matchLabels:
      app: {{ template " ph-ee-connector-mojaloop-java.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template " ph-ee-connector-mojaloop-java.fullname" . }}
      annotations:
{{- if .Values.ph_ee_connector_mojaloop.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_mojaloop.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      affinity: {{ toYaml .Values.ph_ee_connector_mojaloop.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.ph_ee_connector_mojaloop.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.ph_ee_connector_mojaloop.tolerations | default .Values.ph_ee_connector_mojaloop.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.ph_ee_connector_mojaloop.priorityClassName }}
      priorityClassName: {{ .Values.ph_ee_connector_mojaloop.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template " ph-ee-connector-mojaloop-java.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.ph_ee_connector_mojaloop.terminationGracePeriod }}
      containers:
        - name: ph-ee-connector-mojaloop-java
          image: "{{ .Values.ph_ee_connector_mojaloop.image }}:{{ .Values.ph_ee_connector_mojaloop.imageTag }}"
          imagePullPolicy: "{{ .Values.ph_ee_connector_mojaloop.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources: {{ toYaml ( .Values.ph_ee_connector_mojaloop.resources | default .Values.ph_ee_connector_mojaloop.deployment.resources ) | nindent 10 }}
      {{- if .Values.ph_ee_connector_mojaloop.imagePullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.ph_ee_connector_mojaloop.imagePullSecrets | indent 8 }}
        {{- end }}
          livenessProbe:
{{ toYaml .Values.ph_ee_connector_mojaloop.livenessProbe | indent 10 }}
          readinessProbe:
{{ toYaml .Values.ph_ee_connector_mojaloop.readinessProbe | indent 10 }}

          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_mojaloop.SPRING_PROFILES_ACTIVE }}"

            - name: "DFSPIDS"
              value: "{{ .Values.ph_ee_connector_mojaloop.DFSPIDS }}"

            - name: "SWITCH_quotes-host"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.quotes.host }}"

            - name: "SWITCH_quote-service"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.quotes.service }}"

            - name: "SWITCH_als-host"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.als.host }}"

            - name: "SWITCH_account-lookup-service"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.als.service }}"

            - name: "SWITCH_transfers-host"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.transfers.host }}"

            - name: "SWITCH_transfers-service"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.transfers.service }}"

            - name: "SWITCH_transactions-host"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.transactions.host }}"

            - name: "SWITCH_transaction-request-service"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.transactions.service }}"

            - name: "SWITCH_oracle-host"
              value: "{{ .Values.ph_ee_connector_mojaloop.switch.oracle.host }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- if .Values.ph_ee_connector_mojaloop.extraEnvs | default .Values.ph_ee_connector_mojaloop.deployment.extraEnvs }}
{{ toYaml ( .Values.ph_ee_connector_mojaloop.extraEnvs | default .Values.ph_ee_connector_mojaloop.deployment.extraEnvs ) | indent 8 }}
{{- end }}
          envFrom: {{ toYaml ( .Values.ph_ee_connector_mojaloop.envFrom | default .Values.ph_ee_connector_mojaloop.deployment.envFrom ) | nindent 10 }}
          securityContext: {{ toYaml ( .Values.ph_ee_connector_mojaloop.podSecurityContext | default .Values.ph_ee_connector_mojaloop.deployment.securityContext ) | nindent 10 }}

          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
{{- if .Values.ph_ee_connector_mojaloop.deployment.config }}
{{ toYaml .Values.ph_ee_connector_mojaloop.deployment.config | indent 12 }}
{{- end }}            
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
            - -timeout=120s
            - -wait
            - tcp://{{ .Values.operations_app.datasource.host }}:3306
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
    {{ tpl .Values.extraInitContainers . | indent 6 }}
          {{- else }}
    {{ toYaml .Values.extraInitContainers | indent 6 }}
          {{- end }}
          {{- end }}          
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
     {{- if .Values.ph_ee_connector_mojaloop.extraVolumeMounts | default .Values.ph_ee_connector_mojaloop.deployment.extraVolumeMounts }}
  {{ toYaml ( .Values.ph_ee_connector_mojaloop.extraVolumeMounts | default .Values.ph_ee_connector_mojaloop.deployment.extraVolumeMounts ) | indent 8 }}
          {{- end }}
        {{- if .Values.ph_ee_connector_mojaloop.extraContainers }}
  {{ tpl .Values.ph_ee_connector_mojaloop.extraContainers . | indent 6 }}
        {{- end }}            
{{- end }}