{{- if .Values.ph_ee_connector_mojaloop.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-connector-mojaloop-java
  annotations:
{{- if .Values.ph_ee_connector_mojaloop.ingress.annotations }}
{{ toYaml .Values.ph_ee_connector_mojaloop.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.ph_ee_connector_mojaloop.hostname }}"
      http:
        paths:
        - path: "{{ .Values.ph_ee_connector_mojaloop.ingress.path }}"
          pathType: Prefix
          backend:
{{- if .Values.ph_ee_connector_mojaloop.ingress.backend }}
{{ toYaml .Values.ph_ee_connector_mojaloop.ingress.backend | indent 14 }}
{{- end }}

  tls:
  - hosts:
    - "{{ .Values.ph_ee_connector_mojaloop.wildcardhostname }}"
    secretName: "{{ .Values.ph_ee_connector_mojaloop.tls }}"
{{- end }}