# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.ph_ee_connector_slcb.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: {{ template "ph-ee-connector-slcb.fullname" . }}
  labels:
    app: {{ template "ph-ee-connector-slcb.fullname" . }}
spec:
  replicas: {{ .Values.ph_ee_connector_slcb.replicas }}
  selector:
    matchLabels:
      app: {{ template "ph-ee-connector-slcb.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "ph-ee-connector-slcb.fullname" . }}
      annotations:
{{- if .Values.ph_ee_connector_slcb.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_slcb.deployment.annotations | indent 8 }}
{{- end }}

    spec:
      affinity: {{ toYaml .Values.ph_ee_connector_slcb.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.ph_ee_connector_slcb.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.ph_ee_connector_slcb.tolerations | default .Values.ph_ee_connector_slcb.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.ph_ee_connector_slcb.priorityClassName }}
      priorityClassName: {{ .Values.ph_ee_connector_slcb.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "ph-ee-connector-slcb.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.ph_ee_connector_slcb.terminationGracePeriod }}
      containers:
        - name: ph-ee-connector-slcb-mm
          image: "{{ .Values.ph_ee_connector_slcb.image }}"
          imagePullPolicy: "{{ .Values.ph_ee_connector_slcb.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources: {{ toYaml ( .Values.ph_ee_connector_slcb.resources | default .Values.ph_ee_connector_slcb.deployment.resources ) | nindent 10 }}
      {{- if .Values.ph_ee_connector_slcb.imagePullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.ph_ee_connector_slcb.imagePullSecrets | indent 8 }}
        {{- end }}
          livenessProbe:
{{ toYaml .Values.ph_ee_connector_slcb.livenessProbe | indent 10 }}
          readinessProbe:
{{ toYaml .Values.ph_ee_connector_slcb.readinessProbe | indent 10 }}  
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_slcb.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.zeebe_broker_contactpoint }}"
            - name: "SLCB_AUTH_HOST"
              value: "{{ .Values.ph_ee_connector_slcb.auth_host }}"
            - name: "SLCB_AUTH_AUTH-ENDPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.endpoint.auth }}"
            - name: "SLCB_API_HOST"
              value: "{{ .Values.ph_ee_connector_slcb.api_host }}"
            - name: "SLCB_API_TRANSACTION-REQUEST-ENDPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.endpoint.transaction_request }}"
            - name: "SLCB_API_RECONCILIATION-ENDPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.endpoint.reconciliation }}"
            - name: "SLCB_API_ACCOUNT-BALANCE-ENDPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.endpoint.account_balance }}"
            - name: "SLCB_CONFIG_DATE-FROMAT"
              value: "{{ .Values.ph_ee_connector_slcb.config.date_format }}"
            - name: "SLCB_CONFIG_RECONCILIATION_ENABLE"
              value: "{{ .Values.ph_ee_connector_slcb.config.reconciliation.enable }}"
            - name: "SLCB_ACCOUNT_NUMBER"
              value: "{{ .Values.ph_ee_connector_slcb.account_number }}"
            - name: "SLCB_ACCOUNT_TYPE"
              value: "{{ .Values.ph_ee_connector_slcb.account_type }}"
            - name: "SLCB_INSTITUTIONCODE"
              value: "{{ .Values.ph_ee_connector_slcb.institutioncode }}"
            - name: "AWS_BUCKET_NAME"
              value: "{{ .Values.ph_ee_connector_slcb.aws.bucket_name }}"
            - name: "CLOUD_AWS_REGION_STATIC"
              value: "{{ .Values.ph_ee_connector_slcb.aws.region }}"
            - name: "AWS_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "aws-access-key"
            - name: "AWS_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "aws-secret-key"
            - name: "SLCB_AUTH_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-username"  
            - name: "SLCB_AUTH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-password"
            - name: "SLCB_SIGNATURE_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-signature-key"
{{- if .Values.ph_ee_connector_slcb.extraEnvs | default .Values.ph_ee_connector_slcb.deployment.extraEnvs }}
{{ toYaml ( .Values.ph_ee_connector_slcb.extraEnvs | default .Values.ph_ee_connector_slcb.deployment.extraEnvs ) | indent 8 }}
{{- end }}
          envFrom: {{ toYaml ( .Values.ph_ee_connector_slcb.envFrom | default .Values.ph_ee_connector_slcb.deployment.envFrom ) | nindent 10 }}
          securityContext: {{ toYaml ( .Values.ph_ee_connector_slcb.podSecurityContext | default .Values.ph_ee_connector_slcb.deployment.securityContext ) | nindent 10 }}
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
{{- if .Values.ph_ee_connector_slcb.deployment.config }}
{{ toYaml .Values.ph_ee_connector_slcb.deployment.config | indent 12 }}
{{- end }}            
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
            - -timeout=120s
            - -wait
            - tcp://{{ .Values.operations_app.datasource.host }}:3306
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
    {{ tpl .Values.extraInitContainers . | indent 6 }}
          {{- else }}
    {{ toYaml .Values.extraInitContainers | indent 6 }}
          {{- end }}          
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
        {{- if .Values.ph_ee_connector_slcb.extraContainers }}
  {{ tpl .Values.ph_ee_connector_slcb.extraContainers . | indent 6 }}
        {{- end }}                    
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- end }}