# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: {{ template "ph-ee-importer-es.fullname" . }}
  labels:
    app: {{ template "ph-ee-importer-es.fullname" . }}
spec:
  replicas: {{ .Values.importer_es.replicas }}
  selector:
    matchLabels:
      app: {{ template "ph-ee-importer-es.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "ph-ee-importer-es.fullname" . }}
      annotations:
{{- if .Values.importer_es.deployment.annotations }}
{{ toYaml .Values.importer_es.deployment.annotations | indent 8 }}
{{- end }}  
    spec:
      affinity: {{ toYaml .Values.importer_es.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.importer_es.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.importer_es.tolerations | default .Values.importer_es.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.importer_es.priorityClassName }}
      priorityClassName: {{ .Values.importer_es.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "ph-ee-importer-es.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.importer_es.terminationGracePeriod }} 
      containers:
        - name: ph-ee-importer-es
          image: "{{ .Values.importer_es.image }}:{{ .Values.importer_es.imageTag }}"
          imagePullPolicy: "{{ .Values.importer_es.imagePullPolicy }}"
          resources: {{ toYaml ( .Values.importer_es.resources | default .Values.importer_es.deployment.resources ) | nindent 10 }}
      {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.importer_es.imagePullSecrets | indent 8 }}
        {{- end }}
          livenessProbe:
{{ toYaml .Values.importer_es.livenessProbe | indent 10 }}
          readinessProbe:
{{ toYaml .Values.importer_es.readinessProbe | indent 10 }}
          env:
          - name: "reporting.enabled"
            value: "{{ .Values.importer_es.reporting.enabled }}"
          - name: "logging_level_ROOT"
            value: "{{ .Values.importer_es.logging.level.root }}"
          - name: "importer_elasticsearch_url"
            value: "{{ .Values.importer_es.importer_elasticsearch_url }}"
          - name: "JAVA_TOOL_OPTIONS"
            value: "{{ .Values.importer_es.javaToolOptions}}"
          - name: "LOGGING_PATTERN_CONSOLE"
            value: "{{ .Values.importer_es.logging.pattern.console}}"
          - name: "reporting.fields.amount"
            value: "{{ .Values.importer_es.reporting.fields.amount }}"
          - name: "reporting.fields.accountId"
            value: "{{ .Values.importer_es.reporting.fields.accountId }}"
          - name: "reporting.fields.errorCode"
            value: "{{ .Values.importer_es.reporting.fields.errorCode }}"
          - name: "reporting.fields.errorDescription"
            value: "{{ .Values.importer_es.reporting.fields.errorDescription }}"
          - name: "reporting.fields.externalId"
            value: "{{ .Values.importer_es.reporting.fields.externalId }}"
          - name: "reporting.fields.initiator"
            value: "{{ .Values.importer_es.reporting.fields.initiator }}"
          - name: "reporting.fields.initiatorType"
            value: "{{ .Values.importer_es.reporting.fields.initiatorType }}"
          - name: "reporting.fields.isNotificationsFailureEnabled"
            value: "{{ .Values.importer_es.reporting.fields.isNotificationsFailureEnabled }}"
          - name: "reporting.fields.isNotificationsSuccessEnabled"
            value: "{{ .Values.importer_es.reporting.fields.isNotificationsSuccessEnabled }}"
          - name: "reporting.fields.mpesaTransactionId"
            value: "{{ .Values.importer_es.reporting.fields.mpesaTransactionId }}"
          - name: "reporting.fields.mpesaTransactionStatusRetryCount"
            value: "{{ .Values.importer_es.reporting.fields.mpesaTransactionStatusRetryCount }}"
          - name: "reporting.fields.originDate"
            value: "{{ .Values.importer_es.reporting.fields.originDate }}"
          - name: "reporting.fields.partyLookupFailed"
            value: "{{ .Values.importer_es.reporting.fields.partyLookupFailed }}"
          - name: "reporting.fields.phoneNumber"
            value: "{{ .Values.importer_es.reporting.fields.phoneNumber }}"
          - name: "reporting.fields.processDefinitionKey"
            value: "{{ .Values.importer_es.reporting.fields.processDefinitionKey }}"
          - name: "reporting.fields.processInstanceKey"
            value: "{{ .Values.importer_es.reporting.fields.processInstanceKey }}"
          - name: "reporting.fields.scenario"
            value: "{{ .Values.importer_es.reporting.fields.scenario }}"
          - name: "reporting.fields.tenantId"
            value: "{{ .Values.importer_es.reporting.fields.tenantId }}"
          - name: "reporting.fields.timer"
            value: "{{ .Values.importer_es.reporting.fields.timer }}"
          - name: "reporting.fields.timestamp"
            value: "{{ .Values.importer_es.reporting.fields.timestamp }}"
          - name: "reporting.fields.transactionFailed"
            value: "{{ .Values.importer_es.reporting.fields.transactionFailed }}"
          - name: "reporting.fields.transactionId"
            value: "{{ .Values.importer_es.reporting.fields.transactionId }}"
          - name: "reporting.fields.transferCreateFailed"
            value: "{{ .Values.importer_es.reporting.fields.transferCreateFailed }}"
          - name: "reporting.fields.transferSettlementFailed"
            value: "{{ .Values.importer_es.reporting.fields.transferSettlementFailed }}"
          - name: "reporting.fields.transferResponseCREATE"
            value: "{{ .Values.importer_es.reporting.fields.transferResponseCREATE }}"
          - name: "reporting.fields.ams"
            value: "{{ .Values.importer_es.reporting.fields.ams }}"
          - name: "reporting.fields.currency"
            value: "{{ .Values.importer_es.reporting.fields.currency }}"
          - name: "reporting.fields.clientCorrelationId"
            value: "{{ .Values.importer_es.reporting.fields.clientCorrelationId }}"
          - name: "reporting.fields.errorInformation"
            value: "{{ .Values.importer_es.reporting.fields.errorInformation }}"
          - name: "reporting.fields.customData"
            value: "{{ .Values.importer_es.reporting.fields.customData }}"
          - name: "reporting.fields.confirmationReceived"
            value: "{{ .Values.importer_es.reporting.fields.confirmationReceived }}"
          - name: "ELASTICSEARCH_SECURITY_ENABLED"
            value: "{{ .Values.importer_es.elasticsearch_security_enabled }}"
          - name: "ELASTICSEARCH_SSLVERIFICATION"
            value: "{{ .Values.importer_es.elasticsearch_sslverification }}"
          - name: "ELASTICSEARCH_USERNAME"
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: username
          - name: "ELASTICSEARCH_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: password
{{- if .Values.importer_es.extraEnvs | default .Values.importer_es.deployment.extraEnvs }}
{{ toYaml ( .Values.importer_es.extraEnvs | default .Values.importer_es.deployment.extraEnvs ) | indent 8 }}
{{- end }}
          envFrom: {{ toYaml ( .Values.importer_es.envFrom | default .Values.importer_es.deployment.envFrom ) | nindent 10 }}
          securityContext: {{ toYaml ( .Values.importer_es.podSecurityContext | default .Values.importer_es.deployment.securityContext ) | nindent 10 }}
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
{{- if .Values.importer_es.deployment.config }}
{{ toYaml .Values.importer_es.deployment.config | indent 12 }}
{{- end }}               

      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
        {{- if .Values.importer_es.extraContainers }}
  {{ tpl .Values.importer_es.extraContainers . | indent 6 }}
        {{- end }}   

{{- end }}