apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: slcb-secret
type: Opaque
data:
  aws-access-key: {{ .Values.connector_bulk.aws.access_key | b64enc }}
  aws-secret-key: {{ .Values.connector_bulk.aws.secret_key | b64enc }}
  slcb-username: {{ .Values.ph_ee_connector_slcb.username | b64enc }}
  slcb-password: {{ .Values.ph_ee_connector_slcb.password | b64enc }}
  slcb-signature-key: {{ .Values.ph_ee_connector_slcb.signature_key | b64enc }}