{{- if .Values.ph_ee_connector_slcb.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-connector-slcb"
  labels:
    app: ph-ee-connector-slcb
spec:
  replicas: {{ .Values.ph_ee_connector_slcb.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-slcb
  template:
    metadata:
      labels:
        app: ph-ee-connector-slcb
      annotations:
{{- if .Values.ph_ee_connector_slcb.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_slcb.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-slcb-mm
          image: "{{ .Values.ph_ee_connector_slcb.image }}"
          imagePullPolicy: "{{ .Values.ph_ee_connector_slcb.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "{{ .Values.ph_ee_connector_slcb.limits.memory }}"
              cpu: "{{ .Values.ph_ee_connector_slcb.limits.cpu }}"
            requests:
              memory: "{{ .Values.ph_ee_connector_slcb.requests.memory }}"
              cpu: "{{ .Values.ph_ee_connector_slcb.requests.cpu }}"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_slcb.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.zeebe_broker_contactpoint }}"
            - name: "SLCB_AUTH_HOST"
              value: "{{ .Values.ph_ee_connector_slcb.auth_host }}"
            - name: "SLCB_AUTH_AUTH-ENDPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.endpoint.auth }}"
            - name: "SLCB_API_HOST"
              value: "{{ .Values.ph_ee_connector_slcb.api_host }}"
            - name: "SLCB_API_TRANSACTION-REQUEST-ENDPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.endpoint.transaction_request }}"
            - name: "SLCB_API_RECONCILIATION-ENDPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.endpoint.reconciliation }}"
            - name: "SLCB_API_ACCOUNT-BALANCE-ENDPOINT"
              value: "{{ .Values.ph_ee_connector_slcb.endpoint.account_balance }}"
            - name: "SLCB_CONFIG_DATE-FROMAT"
              value: "{{ .Values.ph_ee_connector_slcb.config.date_format }}"
            - name: "SLCB_CONFIG_RECONCILIATION_ENABLE"
              value: "{{ .Values.ph_ee_connector_slcb.config.reconciliation.enable }}"
            - name: "SLCB_ACCOUNT_NUMBER"
              value: "{{ .Values.ph_ee_connector_slcb.account_number }}"
            - name: "SLCB_ACCOUNT_TYPE"
              value: "{{ .Values.ph_ee_connector_slcb.account_type }}"
            - name: "SLCB_INSTITUTIONCODE"
              value: "{{ .Values.ph_ee_connector_slcb.institutioncode }}"
            - name: "AWS_BUCKET_NAME"
              value: "{{ .Values.ph_ee_connector_slcb.aws.bucket_name }}"
            - name: "CLOUD_AWS_REGION_STATIC"
              value: "{{ .Values.ph_ee_connector_slcb.aws.region }}"
            - name: "AWS_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "aws-access-key"
            - name: "AWS_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "aws-secret-key"
            - name: "SLCB_AUTH_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-username"  
            - name: "SLCB_AUTH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-password"
            - name: "SLCB_SIGNATURE_KEY"
              valueFrom:
                secretKeyRef:
                  name: "slcb-secret"
                  key: "slcb-signature-key"  
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: slcb-secret
type: Opaque
data:
  aws-access-key: {{ .Values.connector_bulk.aws.access_key | b64enc }}
  aws-secret-key: {{ .Values.connector_bulk.aws.secret_key | b64enc }}
  slcb-username: {{ .Values.connector_bulk.username | b64enc }}
  slcb-password: {{ .Values.connector_bulk.password | b64enc }}
  slcb-signature-key: {{ .Values.connector_bulk.signature_key | b64enc }}
---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-slcb
  name: ph-ee-connector-slcb
  namespace: default
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-slcb
  sessionAffinity: None
  type: ClusterIP

{{- end }} 
