{{- if .Values.roster_connector.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-connector-ams-roster"
  labels:
    app: ph-ee-connector-ams-roster
spec:
  replicas: {{ .Values.roster_connector.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-ams-roster
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-roster
      annotations:
{{- if .Values.roster_connector.deployment.annotations }}
{{ toYaml .Values.roster_connector.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-ams-roster
          image: "{{ .Values.roster_connector.image }}:{{ Values.roster_connector.imageTag }}"
          ports:
            - containerPort: 5000
          imagePullPolicy: "{{ .Values.roster_connector.imagePullPolicy }}"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.roster_connector.SPRING_PROFILES_ACTIVE }}"
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "zeebe-zeebe-gateway:26500"
            - name: "AMS_LOCAL_ENABLED"
              value: "{{ .Values.roster_connector.ams.local.enabled }}"
            - name: "PESACORE_AUTH-HEADER"
              valueFrom:
                secretKeyRef:
                  name: "roster-secret"
                  key: "auth-token"
            - name: "PESACORE_BASE-URL"
              value: "{{ .Values.roster_connector.pesacore.base_url }}"
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.roster_connector.LOGGING_LEVEL_ROOT }}"
          resources:
            limits:
              memory: "{{ .Values.roster_connector.limits.memory }}"
              cpu: "{{ .Values.roster_connector.limits.cpu }}"
            requests:
              memory: "{{ .Values.roster_connector.requests.memory }}"
              cpu: "{{ .Values.roster_connector.requests.cpu }}"
---
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: roster-secret
type: Opaque
data:
  auth-token: {{ .Values.roster_connector.pesacore.auth_header | b64enc }}
{{- end }}