{{- if .Values.ph_ee_connector_mojaloop.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-connector-mojaloop-java"
  labels:
    app: ph-ee-connector-mojaloop-java
spec:
  replicas: {{ .Values.ph_ee_connector_mojaloop.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-mojaloop-java
  template:
    metadata:
      labels:
        app: ph-ee-connector-mojaloop-java
      annotations:
{{- if .Values.ph_ee_connector_mojaloop.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_mojaloop.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: ph-ee-connector-mojaloop-java
          image: "{{ .Values.ph_ee_connector_mojaloop.image }}:{{ .Values.ph_ee_connector_mojaloop.imageTag }}"
          imagePullPolicy: "{{ .Values.ph_ee_connector_mojaloop.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "{{ .Values.ph_ee_connector_mojaloop.limits.memory }}"
              cpu: "{{ .Values.ph_ee_connector_mojaloop.limits.cpu }}"
            requests:
              memory: "{{ .Values.ph_ee_connector_mojaloop.requests.memory }}"
              cpu: "{{ .Values.ph_ee_connector_mojaloop.requests.cpu }}"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_mojaloop.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config

---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-mojaloop-java
  name: ph-ee-connector-mojaloop-java
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-mojaloop-java
  sessionAffinity: None
  type: ClusterIP

{{- end}}