{{- if .Values.ph_ee_connector_ams_mifos.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "ph-ee-connector-ams-mifos"
  labels:
    app: ph-ee-connector-ams-mifos
spec:
  replicas: {{ .Values.ph_ee_connector_ams_mifos.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-ams-mifos
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-mifos
      annotations:
{{- if .Values.ph_ee_connector_ams_mifos.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.annotations | indent 8 }}
{{- end }}
    spec:   
      containers:
        - name: ph-ee-connector-ams-mifos
          image: "{{ .Values.ph_ee_connector_ams_mifos.image }}:{{ .Values.ph_ee_connector_ams_mifos.imageTag }}"
          imagePullPolicy: "{{ .Values.ph_ee_connector_ams_mifos.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "{{ .Values.ph_ee_connector_ams_mifos.limits.memory }}"
              cpu: "{{ .Values.ph_ee_connector_ams_mifos.limits.cpu }}"
            requests:
              memory: "{{ .Values.ph_ee_connector_ams_mifos.requests.memory }}"
              cpu: "{{ .Values.ph_ee_connector_ams_mifos.requests.cpu }}"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_ams_mifos.SPRING_PROFILES_ACTIVE }}"
            - name: "ams_local_enabled"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_enabled }}"
            - name: "ams_local_interop_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_interop_host }}"
            - name: "ams_local_customer_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_customer_host }}"
            - name: "ams_local_account_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_account_host }}"
            - name: "ams_local_auth_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_auth_host }}"
            - name: "ams_local_tenants"
                value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_tenants.name }}"
                value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_tenants.user }}"
                value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_tenants.password }}"
                value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_tenants.authtype }}"
                value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_tenants.fspId }}"             
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: ph-ee-connector-ams-mifos
  name: ph-ee-connector-ams-mifos
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ph-ee-connector-ams-mifos
  sessionAffinity: None
  type: ClusterIP

---
{{- if .Values.ph_ee_connector_ams_mifos.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-connector-ams-mifos
  annotations:
{{- if .Values.ph_ee_connector_ams_mifos.ingress.annotations }}
{{ toYaml .Values.ph_ee_connector_ams_mifos.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.ph_ee_connector_ams_mifos.hostname }}"
      http:
        paths:
          - path: "{{ .Values.ph_ee_connector_ams_mifos.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.ph_ee_connector_ams_mifos.ingress.backend }}
{{ toYaml .Values.ph_ee_connector_ams_mifos.ingress.backend | indent 14 }}
{{- end }} 

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}

{{- end}}
