{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: ph-ee-importer-es
  labels:
    app: ph-ee-importer-es
spec:
  replicas: {{ .Values.importer_es.replicas }}
  selector:
    matchLabels:
      app: ph-ee-importer-es
  template:
    metadata:
      labels:
        app: ph-ee-importer-es
    spec:
      containers:
        - name: ph-ee-importer-es
          image: "{{ .Values.importer_es.image }}:{{ .Values.importer_es.imageTag }}"
          imagePullPolicy: "{{ .Values.importer_es.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.importer_es.limits.memory }}"
              cpu: "{{ .Values.importer_es.limits.cpu }}"
            requests:
              memory: "{{ .Values.importer_es.requests.memory }}"
              cpu: "{{ .Values.importer_es.requests.cpu }}"
          env:
          - name: "reporting.enabled"
            value: "{{ .Values.importer_es.reporting.enabled }}"
          - name: "logging_level_ROOT"
            value: "{{ .Values.importer_es.logging.level.root }}"
          - name: "JAVA_TOOL_OPTIONS"
            value: "{{ .Values.importer_es.javaToolOptions}}"
          - name: "LOGGING_PATTERN_CONSOLE"
            value: "{{ .Values.importer_es.logging.pattern.console}}"
          - name: "reporting.fields.amount"
            value: "{{ .Values.importer_es.reporting.fields.amount }}"
          - name: "reporting.fields.accountId"
            value: "{{ .Values.importer_es.reporting.fields.accountId }}"
          - name: "reporting.fields.errorCode"
            value: "{{ .Values.importer_es.reporting.fields.errorCode }}"
          - name: "reporting.fields.errorDescription"
            value: "{{ .Values.importer_es.reporting.fields.errorDescription }}"
          - name: "reporting.fields.externalId"
            value: "{{ .Values.importer_es.reporting.fields.externalId }}"
          - name: "reporting.fields.initiator"
            value: "{{ .Values.importer_es.reporting.fields.initiator }}"
          - name: "reporting.fields.initiatorType"
            value: "{{ .Values.importer_es.reporting.fields.initiatorType }}"
          - name: "reporting.fields.isNotificationsFailureEnabled"
            value: "{{ .Values.importer_es.reporting.fields.isNotificationsFailureEnabled }}"
          - name: "reporting.fields.isNotificationsSuccessEnabled"
            value: "{{ .Values.importer_es.reporting.fields.isNotificationsSuccessEnabled }}"
          - name: "reporting.fields.mpesaTransactionId"
            value: "{{ .Values.importer_es.reporting.fields.mpesaTransactionId }}"
          - name: "reporting.fields.mpesaTransactionStatusRetryCount"
            value: "{{ .Values.importer_es.reporting.fields.mpesaTransactionStatusRetryCount }}"
          - name: "reporting.fields.originDate"
            value: "{{ .Values.importer_es.reporting.fields.originDate }}"
          - name: "reporting.fields.partyLookupFailed"
            value: "{{ .Values.importer_es.reporting.fields.partyLookupFailed }}"
          - name: "reporting.fields.phoneNumber"
            value: "{{ .Values.importer_es.reporting.fields.phoneNumber }}"
          - name: "reporting.fields.processDefinitionKey"
            value: "{{ .Values.importer_es.reporting.fields.processDefinitionKey }}"
          - name: "reporting.fields.processInstanceKey"
            value: "{{ .Values.importer_es.reporting.fields.processInstanceKey }}"
          - name: "reporting.fields.scenario"
            value: "{{ .Values.importer_es.reporting.fields.scenario }}"
          - name: "reporting.fields.tenantId"
            value: "{{ .Values.importer_es.reporting.fields.tenantId }}"
          - name: "reporting.fields.timer"
            value: "{{ .Values.importer_es.reporting.fields.timer }}"
          - name: "reporting.fields.timestamp"
            value: "{{ .Values.importer_es.reporting.fields.timestamp }}"
          - name: "reporting.fields.transactionFailed"
            value: "{{ .Values.importer_es.reporting.fields.transactionFailed }}"
          - name: "reporting.fields.transactionId"
            value: "{{ .Values.importer_es.reporting.fields.transactionId }}"
          - name: "reporting.fields.transferCreateFailed"
            value: "{{ .Values.importer_es.reporting.fields.transferCreateFailed }}"
          - name: "reporting.fields.transferSettlementFailed"
            value: "{{ .Values.importer_es.reporting.fields.transferSettlementFailed }}"
          - name: "reporting.fields.transferResponseCREATE"
            value: "{{ .Values.importer_es.reporting.fields.transferResponseCREATE }}"
          - name: "ELASTICSEARCH_SECURITY_ENABLED"
            value: "{{ .Values.importer_es.elasticsearch_security_enabled }}"
          - name: "ELASTICSEARCH_SSLVERIFICATION"
            value: "{{ .Values.importer_es.elasticsearch_sslverification }}"
          - name: "ELASTICSEARCH_USERNAME"
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: username
          - name: "ELASTICSEARCH_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: elastic-credentials
                key: password

{{- end }}
