{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: ph-ee-operations-web
  labels:
    app: ph-ee-operations-web
spec:
  replicas: {{ .Values.operations_web.replicas }}
  selector:
    matchLabels:
      app: ph-ee-operations-web
  template:
    metadata:
      labels:
        app: ph-ee-operations-web
      annotations:
{{- if .Values.operations_web.deployment.annotations }}
{{ toYaml .Values.operations_web.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-operations-web
          image: "{{ .Values.operations_web.image }}"
          imagePullPolicy: "{{ .Values.operations_web.imagePullPolicy }}"
          ports:
            - containerPort: 4200
          resources:
            limits:
              memory: "{{ .Values.operations_web.limits.memory }}"
              cpu: "{{ .Values.operations_web.limits.cpu }}"
            requests:
              memory: "{{ .Values.operations_web.requests.memory }}"
              cpu: "{{ .Values.operations_web.requests.cpu }}"
          volumeMounts:
            - name: ph-ee-operations-web-config
              mountPath: "/app/src/assets/configuration.properties"
              subPath: "configuration.properties"
      volumes:
        - name: ph-ee-operations-web-config
          configMap:
            name: ph-ee-operations-web-config

---
apiVersion: {{ .Values.configmap.apiversion }}
kind: ConfigMap
data:
  configuration.properties: |
    oauth.enabled true
    oauth.basicAuth true
    oauth.basicAuthToken Y2xpZW50Og==
    oauth.serverUrl http://{{ .Values.identity.hostname }}
    serverUrl http://{{ .Values.operations_app.hostname }}
metadata:
  name: ph-ee-operations-web-config

---
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  name: ph-ee-operations-web
spec:
  selector:
    app: ph-ee-operations-web
  ports:
    - protocol: TCP
      port: 4200

---
{{- if .Values.operations_web.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiversion }}
kind: Ingress
metadata:
  name: ph-ee-operations-web
  annotations:
{{- if .Values.operations_web.ingress.annotations }}
{{ toYaml .Values.operations_web.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.operations_web.hostname }}"
      http:
        paths:
          - path: "{{ .Values.operations_web.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.operations_web.ingress.backend }}
{{ toYaml .Values.operations_web.ingress.backend | indent 14 }}
{{- end }}

  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}
{{- end }}
