apiVersion: v2
description: PaymentHub EE Barebone Edition
type: application
name: ph-ee-g2psandbox-security
version: 0.0.0
appVersion: 0.0.0

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine-0.0.0-SNAPSHOT
  version: 0.0.0-SNAPSHOT