apiVersion: v2
description: PaymentHub EE Barebone Edition
type: application
name: ph-ee-g2psandbox-security
version: 1.4.0
appVersion: 1.4.0

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine-1.13.0-SNAPSHOT
  version: 1.13.0-SNAPSHOT
