apiVersion: v2
description: PaymentHub EE Barebone Edition
type: application
name: ph-ee-g2psandbox-security
version: 1.4.1
appVersion: 1.4.1

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine-1.13.2-SNAPSHOT
  version: 1.13.2-SNAPSHOT
- name: konga
  version: 1.0.0
  repository:  https://fynarfin.io/images/konga/
