dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine-0.0.0-SNAPSHOT.tgz
  version: 0.0.0-SNAPSHOT


- name: ph_ee_identity_account_mapper
  repository: "file://././identity-account-mapper/account-mapper"
  version: 1.0.0